const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
require('dotenv').config({ path: path.join(__dirname, '../../.env') });
const { getDb, initDb } = require('./db');

(async () => {
  await initDb();
  const db = getDb();
  console.log('Querying database for any jobs containing test, mock, or placeholder terms...');
  const res = await db.execute(`
    SELECT id, job_name, organization, official_application_link 
    FROM jobs 
    WHERE job_name LIKE '%test%' 
       OR job_name LIKE '%mock%' 
       OR job_name LIKE '%placeholder%'
       OR job_name LIKE '%dummy%'
       OR organization LIKE '%test%'
       OR organization LIKE '%mock%'
       OR organization LIKE '%placeholder%'
       OR organization LIKE '%dummy%'
  `);
  console.log(`Found ${res.rows.length} suspect jobs.`);
  res.rows.forEach(r => {
    console.log(`- [${r.id}] Name: "${r.job_name}" | Org: "${r.organization}" | Link: "${r.official_application_link}"`);
  });
  
  console.log('\nChecking for any jobs not generated by seed...');
  const allSeededJobsRes = await db.execute("SELECT id FROM jobs");
  console.log(`Total jobs in DB: ${allSeededJobsRes.rows.length}`);
  process.exit(0);
})();
